# Generated by Django 5.2 on 2025-04-26 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=200)),
                ('apartment', models.CharField(blank=True, help_text='Piso, apto, unidad, etc.', max_length=50, null=True)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='Colombia', max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.client')),
            ],
        ),
    ]
