# Generated by Django 5.2 on 2025-04-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
